name: test
on:
    push:
        branches: ["*"] 

    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [16.x]	

        env:
            MYSQL_HOST: "{{ secrets.MYSQL_HOST }}"        
            MYSQL_ROOT_PASSWORD: "{{ secrets.MYSQL_ROOT_PASSWORD }}"
            MYSQL_USER: "{{ secrets.MYSQL_USER }}"
            MYSQL_PASSWORD: "{{ secrets.MYSQL_PASSWORD }}"
            MYSQL_DATABASE: "{{ secrets.MYSQL_DATABASE }}"

        steps:
            - name: Checkout repository code  
              uses: actions/checkout@v3 
            - name: Setup MySQL
              run: |
                    sudo /etc/init.d/mysql start
                    mysql -uroot -p'{{ secrets.MYSQL_ROOT_PASSWORD }}' -h 127.0.0.1 -e "CREATE DATABASE {{ secrets.MYSQL_DATABASE }};"
                    mysql -uroot -p'{{ secrets.MYSQL_ROOT_PASSWORD }}' -h 127.0.0.1 sparkdb < ./spark-backend/db/backup.sql
                    
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm install
            - run: npm test
    build:
      needs: test
      uses: ./.github/workflows/build.yml
      secrets: inherit
